select *
from customer limit 20

-- 1. what is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as revenue
From customer
group by gender
-- 2. which customers used a discount but still spent more than the average purchase amount?
(select customer_id,purchase_amount 
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount)
														from customer))
-- 3. which are top 5  products with highest average review rating?
select item_purchased,Round(avg(review_rating::numeric),2) as "average_rating" -- for rount=ding to 2 decimals
from customer
group by item_purchased
order by avg(review_rating) DESC
limit 5;

-- 4 compare the avg purchase amounts between standard and express shipping?
select shipping_type, Round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type
-- 5 do subscribed customers spend more ? compare the avg spend and total revenue between 
--   subscribers and non subscribers
select subscription_status, count(customer_id) as total_customers,
round(avg(purchase_amount),2) as average_spend_amount,
ROUND(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, average_spend_amount DESC;
-- 6 which 5 products havethe highest percentage of purchases with discount applied?
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 END)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate DESC
limit 5;
-- 7 segment customers into new, returning and loyal based on their total number of previous purchases ,
-- and show count of each segment
with customer_type as(
select customer_id,previous_purchases,
case 
	when previous_purchases = 1 then 'new'
	when previous_purchases between 2 and 10 then 'Returning'
	Else 'Loyal'
	END as customer_segment
from customer
)
select customer_segment,count(*) as "number_of_customer"
from customer_type
group by customer_segment
-- 8 what are the top 3 most purchased products within each category?
with item_count as (
select category, item_purchased, count(customer_id) as total_orders,
row_number()over(partition by category order by count(customer_id)DESC) as item_rank
from customer
group by category, item_purchased
)
select item_rank,category,item_purchased, total_orders
from item_count
where item_rank <= 3;

-- 9 are customers who are repeat buyers (more than 5 previous purchases ) also lickly to subscribe
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

-- 10 what is the revenue contribution of each age group

select age_group,
sum(purchase_amount)as total_revenue
from customer
group by age_group
order by total_revenue desc